apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler

metadata:
  name: sre-webapp-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sre-webapp

  minReplicas: 2
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50